# Generated by Django 2.2.3 on 2019-09-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190919_0334'),
        ('main_app', '0003_auto_20190918_2137'),
    ]

    operations = [
    ]
